name: Add Version Tag

permissions:
  id-token: write
  contents: write

on:
  push:
    branches:
      - main

jobs:
  release_commit_check:
    runs-on: ubuntu-latest
    outputs:
        release_commit_check: ${{ steps.check_version_bump.outputs.release_commit_check }}
        new_version: ${{ steps.check_version_bump.outputs.new_version }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Check For Version Bump
        id: check_version_bump
        run: |
          MESSAGE="${{ github.event.head_commit.message }}"
          BUMP_REGEX="^chore\([0-9]\.[0-9]\.[0-9]\): update pyproject version.*"
          BUMP_MATCH=$(echo ${MESSAGE} | egrep "${BUMP_REGEX}") || true # Prevent error code on no match
          if [ -n "${BUMP_MATCH}" ]
          then
            NEW_VERSION=$(echo $BUMP_MATCH | sed -E "s/chore\(|\): update pyproject version.*//g")
            echo "release_commit_check=true" >> $GITHUB_OUTPUT
            echo "new_version=${NEW_VERSION}" >> $GITHUB_OUTPUT
          fi

  add_version:
    runs-on: ubuntu-latest
    needs: release_commit_check
    if: ${{ needs.release_commit_check.outputs.release_commit_check == 'true' }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Add Version Tag
        uses: rickstaa/action-create-tag@v1
        with:
          tag: ${{ needs.release_commit_check.outputs.new_version }}
          commit_sha: ${{ github.sha }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
