name: Build and Deploy

on:
  push:
    branches:
      # TODO: Switch back to main
      - zn_dockerhub
    tags:
      - '\d+.\d+.\d+'

permissions:
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Login to Dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build, Tag, and Push Docker Image
        run: |
          # TODO: Add -p (push) flag
          ci/docker-build-image

