name: Build and Deploy

on:
  push:
    branches:
      - main
    tags:
      - '\d+.\d+.\d+'

permissions:
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Login to Dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build, Tag, and Push Docker Image
        run: |
          ci/docker-build-image -p

