name: Create Release

on:
  push:
    tags: '\d+.\d+.\d+'

jobs:
  on-main-branch-check:
    runs-on: ubuntu-latest
    outputs:
      on_main: ${{ steps.contains_tag.outputs.retval }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: rickstaa/action-contains-tag@v1
        id: contains_tag
        with:
          reference: "main"
          tag: "${{ github.ref_name }}"

  draft_changelog:
    runs-on: ubuntu-latest
    needs: on-main-branch-check
    if: ${{ needs.on-main-branch-check.outputs.on_main == 'true' }}
    outputs:
      release_body: ${{ steps.git_cliff.outputs.content }}
    steps:
      - name: Checkout Repository at Tagged Commit
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.ref_name }}
      - name: Generate Changelog
        id: git_cliff
        uses: orhun/git-cliff-action@v4
        with:
          args: --latest --verbose
        env:
          GITHUB_REPO: ${{ github.repository }}

  create_github_release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: read
    needs: draft_changelog
    steps:
      - name: Create Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: ${{ github.ref_name }}
          body: |
            ${{ needs.draft_changelog.outputs.release_body }}
          draft: false
          prerelease: false
