name: Trigger Version Bump

permissions:
  pull-requests: write
  contents: write

on:
  workflow_dispatch:
    inputs:
      version:
        description: Version to be applied. Must be greater than current version.
        required: true
        type: string
  push:
    branches:
      - zn_versioning #TODO: remove on push trigger

env:
  POETRY_VERSION: 1.8.2

jobs:
  update_version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-tags: true
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Git Credentials
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Install poetry
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry==${{env.POETRY_VERSION}}

      - name: Update pyproject.toml, commit
        id: update-version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # TODO: Switch version from 9.9.9 to ${{ inputs.version }}
        # TODO: Remove git checkout zn_versioning
        run: |
          git checkout zn_versioning
          PR_BRANCH=ci_release_branch_$(date +"%Y%d%m.%H%M%S")
          git checkout -b ${PR_BRANCH}
          ci/update-version -v 9.9.9 -c
          echo "PR_BRANCH=${PR_BRANCH}" >> ${GITHUB_OUTPUT}
      
      - name: Push and Open Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # TODO: Switch base from zn_versioning to main
        run: |
          git push --set-upstream origin ${{ steps.update-version.outputs.PR_BRANCH }}
          gh pr create \
            --base zn_versioning \
            --head ${{ steps.update-version.outputs.PR_BRANCH }} \
            --title "$(git log -1 --pretty=%B)" \
            --body "Update version in pyproject.toml to trigger release."
